"use client";

// src/app/auth/accept/page.tsx
//
// Landing page for the invite/recovery link generated by the admin
// provisioning endpoint (Phase 1, members/route.ts createAndInvite).
// Supabase's action_link redirects here with either a PKCE ?code= or a
// hash-fragment token; createBrowserClient's detectSessionInUrl:true (the
// default) auto-exchanges it into a session on load — same mechanism as
// /auth/callback, and for the same reason we don't call
// exchangeCodeForSession() manually here either (double-exchange fails).
//
// Once a session exists, the user sets their own password (Option A: no
// plaintext password ever transited email) using the exact same complexity
// policy as the super-admin system (src/lib/imotara/passwordPolicy.ts).

import { Suspense, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { createBrowserClient } from "@supabase/ssr";
import { checkPasswordComplexity, PASSWORD_POLICY } from "@/lib/imotara/passwordPolicy";
import EyeIcon from "@/components/imotara/EyeIcon";

const supabaseAccept = createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
);

type Step = "verifying" | "set_password" | "saving" | "done" | "error" | "session_lost";

function AcceptHandler() {
    const router = useRouter();
    const [step, setStep] = useState<Step>("verifying");
    const [error, setError] = useState<string | null>(null);
    const [password, setPassword] = useState("");
    const [confirm, setConfirm] = useState("");
    const [fieldError, setFieldError] = useState<string | null>(null);
    const [showPassword, setShowPassword] = useState(false);

    useEffect(() => {
        let settled = false;

        // Supabase's invite/recovery action_link redirects here with tokens
        // in the URL HASH (#access_token=...&refresh_token=...) — the older
        // implicit-grant style, not a PKCE ?code=. createBrowserClient from
        // @supabase/ssr hardcodes flowType:"pkce", so its automatic
        // detectSessionInUrl only watches for ?code= and never picks up a
        // hash-based token — the session was never being established at all.
        // Parse the hash ourselves and call setSession() explicitly.
        const hashParams  = new URLSearchParams(window.location.hash.replace(/^#/, ""));
        const accessToken  = hashParams.get("access_token");
        const refreshToken = hashParams.get("refresh_token");

        if (accessToken && refreshToken) {
            supabaseAccept.auth.setSession({ access_token: accessToken, refresh_token: refreshToken })
                .then(({ data: { session }, error: setSessionErr }) => {
                    if (settled) return;
                    if (session && !setSessionErr) {
                        settled = true;
                        // Clear the tokens from the visible URL now that they're consumed.
                        window.history.replaceState(null, "", window.location.pathname);
                        setStep("set_password");
                    } else {
                        settled = true;
                        setError("This invite link is invalid or has already been used.");
                        setStep("error");
                    }
                });
        }

        // Fallback: also watch for a session the normal (PKCE) way, in case
        // this page is ever reached via a different link type.
        supabaseAccept.auth.getSession().then(({ data: { session } }) => {
            if (session && !settled) { settled = true; setStep("set_password"); }
        });

        const { data: { subscription } } = supabaseAccept.auth.onAuthStateChange((event, session) => {
            if (settled) return;
            if (event === "SIGNED_IN" && session) {
                settled = true;
                setStep("set_password");
            }
        });

        const fallback = setTimeout(() => {
            if (!settled) {
                settled = true;
                setError("This invite link has expired or is invalid. Ask whoever invited you to send a new one.");
                setStep("error");
            }
        }, 10_000);

        return () => {
            subscription.unsubscribe();
            clearTimeout(fallback);
        };
    }, []);

    async function handleSubmit(e: React.FormEvent) {
        e.preventDefault();
        setFieldError(null);

        const check = checkPasswordComplexity(password);
        if (!check.ok) { setFieldError(check.reason ?? "Password does not meet the requirements."); return; }
        if (password !== confirm) { setFieldError("Passwords do not match."); return; }

        setStep("saving");

        // Force a fresh session check right before the write. getSession()
        // transparently refreshes an expired access token using the refresh
        // token already in the client — without this, a session established
        // by setSession() minutes earlier (while the user was reading the
        // password policy, typing, retyping) can have gone stale by the time
        // we actually submit, since it's easy for more time to pass here than
        // the access token's lifetime. Confirmed as the real trigger via a
        // live report — this isn't a hypothetical edge case.
        const { data: { session: freshSession } } = await supabaseAccept.auth.getSession();
        if (!freshSession) {
            setStep("session_lost");
            return;
        }

        const { error: updateErr } = await supabaseAccept.auth.updateUser({ password });
        if (updateErr) {
            // "Auth session missing" (and similar) means the session this page
            // established has since gone away — retrying the same updateUser()
            // call here will just fail identically forever, since nothing
            // re-establishes it. Route to a real recovery path instead of
            // silently dropping the user back on a form that can never succeed.
            const sessionLost = /session/i.test(updateErr.message ?? "");
            if (sessionLost) {
                setStep("session_lost");
                return;
            }
            setFieldError(updateErr.message || "Could not set your password. Please try again.");
            setStep("set_password");
            return;
        }

        // Best-effort audit trail — never block the user's own access on this.
        fetch("/api/org/accept-confirm", { method: "POST" }).catch(() => {});

        setStep("done");
        setTimeout(() => router.replace("/org/dashboard"), 1200);
    }

    if (step === "verifying") {
        return <p className="text-sm text-zinc-500 dark:text-zinc-400">Verifying your invite…</p>;
    }

    if (step === "error") {
        return (
            <div className="text-center">
                <p className="text-sm text-red-600 dark:text-red-400">{error}</p>
            </div>
        );
    }

    if (step === "done") {
        return <p className="text-sm text-zinc-500 dark:text-zinc-400">Password set — taking you to your dashboard…</p>;
    }

    if (step === "session_lost") {
        return (
            <div className="w-full max-w-sm text-center">
                <p className="text-sm text-red-600 dark:text-red-400">
                    Your session has expired, so we can&apos;t save this password. This can happen if the link sat open for a while, or a newer invite was sent to this email since.
                </p>
                <Link
                    href="/auth/forgot-password"
                    className="mt-4 inline-flex w-full items-center justify-center rounded-lg bg-zinc-900 px-4 py-2 text-sm font-medium text-white transition hover:bg-zinc-700 dark:bg-white dark:text-zinc-900 dark:hover:bg-zinc-200"
                >
                    Request a new link
                </Link>
            </div>
        );
    }

    return (
        <div className="w-full max-w-sm">
            <h1 className="text-lg font-semibold text-zinc-900 dark:text-zinc-50">Set your password</h1>
            <p className="mt-1 text-sm text-zinc-500 dark:text-zinc-400">
                Choose a password to finish accepting your invite.
            </p>

            <form onSubmit={handleSubmit} className="mt-6 space-y-4">
                <div>
                    <label htmlFor="password" className="mb-1 block text-xs font-medium text-zinc-600 dark:text-zinc-400">
                        New password
                    </label>
                    <div className="relative">
                        <input
                            id="password"
                            type={showPassword ? "text" : "password"}
                            autoComplete="new-password"
                            value={password}
                            onChange={(e) => setPassword(e.target.value)}
                            className="w-full rounded-lg border border-zinc-300 bg-white px-3 py-2 pr-10 text-sm text-zinc-900 outline-none focus:border-zinc-500 dark:border-zinc-700 dark:bg-zinc-950 dark:text-zinc-100"
                        />
                        <button
                            type="button"
                            onClick={() => setShowPassword((v) => !v)}
                            aria-label={showPassword ? "Hide password" : "Show password"}
                            className="absolute right-3 top-1/2 -translate-y-1/2 text-zinc-500 hover:text-zinc-300"
                        >
                            <EyeIcon open={showPassword} />
                        </button>
                    </div>
                    <p className="mt-1 text-[11px] text-zinc-500 dark:text-zinc-500">{PASSWORD_POLICY}</p>
                </div>

                <div>
                    <label htmlFor="confirm" className="mb-1 block text-xs font-medium text-zinc-600 dark:text-zinc-400">
                        Confirm password
                    </label>
                    <div className="relative">
                        <input
                            id="confirm"
                            type={showPassword ? "text" : "password"}
                            autoComplete="new-password"
                            value={confirm}
                            onChange={(e) => setConfirm(e.target.value)}
                            className="w-full rounded-lg border border-zinc-300 bg-white px-3 py-2 pr-10 text-sm text-zinc-900 outline-none focus:border-zinc-500 dark:border-zinc-700 dark:bg-zinc-950 dark:text-zinc-100"
                        />
                        <button
                            type="button"
                            onClick={() => setShowPassword((v) => !v)}
                            aria-label={showPassword ? "Hide password" : "Show password"}
                            className="absolute right-3 top-1/2 -translate-y-1/2 text-zinc-500 hover:text-zinc-300"
                        >
                            <EyeIcon open={showPassword} />
                        </button>
                    </div>
                </div>

                {fieldError && (
                    <p role="alert" className="text-xs text-red-600 dark:text-red-400">{fieldError}</p>
                )}

                <button
                    type="submit"
                    disabled={step === "saving"}
                    className="w-full rounded-lg bg-zinc-900 px-4 py-2 text-sm font-medium text-white transition hover:bg-zinc-700 disabled:opacity-50 dark:bg-white dark:text-zinc-900 dark:hover:bg-zinc-200"
                >
                    {step === "saving" ? "Saving…" : "Set password & continue"}
                </button>
            </form>
        </div>
    );
}

export default function AcceptPage() {
    return (
        <div className="flex min-h-screen items-center justify-center px-4 py-14 text-zinc-900 dark:text-zinc-50">
            <Suspense>
                <AcceptHandler />
            </Suspense>
        </div>
    );
}
